//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cultivation
    {
        public int Id { get; set; }
        public int Id_Field { get; set; }
        public string State { get; set; }
        public string What { get; set; }
    
        public virtual Field Field { get; set; }
    }
}
