//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplikacja.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class farmEntities : DbContext
    {
        public farmEntities()
            : base("name=farmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Animal_History> Animal_History { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cultivation> Cultivations { get; set; }
        public virtual DbSet<Farmer> Farmers { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Field_History> Field_History { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<Animal_Breed> Animal_Breed { get; set; }
        public virtual DbSet<Seed> Seeds { get; set; }
    }
}
